apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: sonarqube-bundled
runs:
  using: composite
  steps:
    - id: sonarqube
      name: sonarqube-bundled
      uses: docker://registry.saas-dev.beescloud.com/staging/sonarscanner-actions:main-52f49e484d68cffeb2f11a590923dd9fdc616c1b
      shell: bash
      env:
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{ step.internal.id }}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }} 
        CONFIG_JSON: '{"actor":"${{ cloudbees.event.head_commit.author.username }}","tenent_info":"default_tenant","asset_uuid":"c6cef160-c0b3-43a4-bda1-53ab484cc9da","profile_uuid":"profile-uuid-1","asset_identifier":"${{ cloudbees.scm.repositoryUrl }}","profile_identifier":"${{ cloudbees.scm.branch }}"}'
      run: |
        set -x
        cd /
        echo "RUN ID: ${{ cloudbees.run_id }}"
        echo "Job ID: ${{ job.id }}"
        echo "Step ID: ${{ step.internal.id }}"
        /bin/bash -c "/usr/local/bin/scan.sh"