= CloudBees action: Scan with SonarQube bundled

If you do not have a centralized SonarQube already installed, use this action to scan a Git repository with the SonarQube static application security testing (SAST) scanner, which detects security flaws and provides suggested code fixes.
SonarQube scan results are displayed in CloudBees platform analytics dashboards, but not in SonarQube reports, as the SonarQube instance is headless/ephemeral.

For code coverage information, you have to use a third-party coverage tool, as SonarQube itself does not calculate coverage.
Configure the SonarQube bundled action to import coverage results by either specifying a coverage file or running a unit test.

NOTE: If you already are running a centralized SonarQube, use the link:https://github.com/cloudbees-io/sonarqube-sast-scan-code[Scan with SonarQube action] instead.

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `sonar-exclusion`
| String
| No
| SonarQube Exclusion pattern to exclude matching files.

| `sonar-inclusion`
| String
| No
| SonarQube Inclusion pattern to include matching files.

| `cover-file-name`
| String
| No
| The file path of the third-party code coverage tool results.

| `language`
| String
| Yes
| The language of your Git repository code base.
Refer to <<_supported_languages>>.

| `log-level`
| String
| No
| Log level. Can be `INFO`, `DEBUG`, or `TRACE`.

| `threshold-critical`
| integer
| No
| The number threshold of critical severity vulnerabilities at which the build is broken.

| `threshold-very-high`
| integer
| No
| The number threshold of very high severity vulnerabilities at which the build is broken.

| `threshold-high`
| integer
| No
| The number threshold of high severity vulnerabilities at which the build is broken.

| `threshold-medium`
| integer
| No
| The number threshold of medium severity vulnerabilities at which the build is broken.

| `threshold-low`
| integer
| No
| The number threshold of low severity vulnerabilities at which the build is broken.

|===

[#_supported_languages]
== Supported languages

[cols="1a,1a",options="header"]
.Supported languages with inputs
|===

| Supported language
| Input format

| Go
| `LANGUAGE_GO`

| Java
| `LANGUAGE_JAVA`

| JavaScript
| `LANGUAGE_JS`

| PHP
| `LANGUAGE_PHP`

| Python
| `LANGUAGE_PYTHON`

| Ruby
| `LANGUAGE_RUBY`

| Dotnet
| `LANGUAGE_DOTNET`
|===

== Usage example

In your YAML file, add:

[source,yaml]
----

      - name: Scan with SonarQube bundled
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        with:
          sonar-exclusion: sonar/*
          cover-file-name: ./coverage.xml
          language: LANGUAGE_PYTHON
----

In the following example, if there are any critical, very high, high, medium or low severity vulnerabilities identified, the build is broken.

[source,yaml]
----
      - name: Scan with SonarQube bundled
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        with:
          sonar-exclusion: sonar/*
          cover-file-name: ./coverage.xml
          language: LANGUAGE_PYTHON
          threshold-critical: 0
          threshold-very-high: 0
          threshold-high: 0
          threshold-medium: 0
          threshold-low: 0
----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform/latest/actions[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform/latest/[the CloudBees platform].
